substitutions:
  API_KEY: "NQBcjzWnTbS4GpeEhWgjV0O5GHoM+crIWZe/V3F021Q="
  OTA_PASSWORD: "5ms7qBRHVIstwhF3+SAh/NC2uhpOPIST"
  PROD_MANIFEST_URL: "https://morganmlg.com/Carb-O-nated-Pro/manifest.json"
  BETA_MANIFEST_URL: "https://morganmlg.com/Carb-O-nated-Pro/manifest-beta.json"
  WEB_USERNAME: "esphome"
  WEB_PASSWORD: "esphome"
  AP_SSID: "Carb-O-nated-Pro"
  AP_PASSWORD: "esphome-fallback"

esphome:
  name: carb-o-nated-pro
  friendly_name: "Carb-O-nated-Pro"
  comment: "ESP32 based DoYouHost project"
  name_add_mac_suffix: true
  project:
    name: "DoYouHost.Carb-O-nated-Pro"
    version: "dev"

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

dashboard_import:
  package_import_url: github://DoYouHost/Carb-O-nated-Pro/esp32-carb-o-nated-pro.yml@main
  import_full_config: false

packages:
  DoYouHost/ESPHomeTemplates:
    url: https://github.com/DoYouHost/ESPHomeTemplates
    files:
      - basic.yaml
      - debug.yaml
      - updateBetaProdStaging.yaml
      - wifiInfo.yaml
    ref: main
    refresh: 0d

wifi:
  reboot_timeout: 15min
  enable_btm: true
  enable_rrm: true
  ap:
    ssid: "${AP_SSID}"
    password: "${AP_PASSWORD}"

captive_portal:

improv_serial:

api:
  reboot_timeout: 15min
  encryption:
    key: "${API_KEY}"

ota:
  - platform: esphome
    password: "${OTA_PASSWORD}"
